name: DrawBot App Builder

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Set up Python 3.7
      run:
        brew update
        brew install python
    - name: Check python
      run: |
        python3 --version
        python3 -c "import platform; print('macOS version:', platform.mac_ver()[0])"
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python3 -m pip install -r ./requirements.txt
        python3 -m pip install -r ./test-requirements.txt
        python3 -m pip install .
    - name: Run tests
      run: python3 ./tests/runAllTests.py
    - name: Build app
      if: success()
      run: |
        python3 setupApp.py py2app --dmg
    - name: Create Release
      if: success()
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
        body: |
          !!!Edit the Release note!!!
    - name: Upload Release Asset
      if: success()
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./dist/DrawBot.dmg
        asset_name: DrawBot.dmg
        asset_content_type: application/dmg

