name: DrawBot

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: macOS-10.13

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python3 -m pip install -r ./test-requirements.txt
        python3 -m pip install codecov
    - name: Run tests
      run: coverage run ./tests/runAllTests.py
    - name: Storing artifacts
      uses: actions/upload-artifact@master
      with:
        name: DrawBot Temp Data Results
        path: ./tests/tempTestData
