name: DrawBot

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: macOS-10.14

    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Check python
      run: |
        python --version
        python -c "import platform; print('macOS version:', platform.mac_ver()[0])"
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install -r ./test-requirements.txt
        python -m pip install .
        python -m pip install codecov
    - name: Run tests
      run: coverage run ./tests/runAllTests.py
    - name: Storing Test Data Artifacts
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: DrawBot Temp Data Results
        path: ./tests/tempTestData
    - name: Building Test Differences
      if: failure()
      run: |
        python ./tests/testDataDifferenceBuilder.py ./tests/tempTestData ./tests/testDifferences.pdf
    - name: Storing Test Differences
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: DrawBot Test Differences
        path: ./tests/testDifferences.pdf

